services:
  reservation:
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: pnpm run start:dev reservation
    env_file:
      - ./apps/reservation/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      TZ: Asia/Seoul
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    environment:
      TZ: Asia/Seoul
  mongo:
    image: mongo
    environment:
      TZ: Asia/Seoul
