services:
  reservation:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./apps/reservation/Dockerfile
      target: development
    command: pnpm run start:dev reservation
    env_file:
      - ./apps/reservation/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      TZ: Asia/Seoul
  auth:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    environment:
      TZ: Asia/Seoul
  payment:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./apps/payment/Dockerfile
      target: development
    command: pnpm run start:dev payment
    env_file:
      - ./apps/payment/.env
    volumes:
      - .:/usr/src/app
    environment:
      TZ: Asia/Seoul
  notification:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./apps/notification/Dockerfile
      target: development
    command: pnpm run start:dev notification
    env_file:
      - ./apps/notification/.env
    volumes:
      - .:/usr/src/app
    environment:
      TZ: Asia/Seoul
  mongo:
    image: mongo
    environment:
      TZ: Asia/Seoul
