apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservation
  name: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
      - image: asia-northeast3-docker.pkg.dev/nestjs-pnpm/reservation/prod
        name: reservation
        env:
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: connectionString
          - name: HTTP_PORT
            value: '3004'
          - name: AUTH_HOST
            value: auth-tcp
          - name: AUTH_PORT
            value: '3002'
          - name: PAYMENT_HOST
            value: payment
          - name: PAYMENT_PORT
            value: '3001'
        ports:
          - containerPort: 3004
