apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - image: asia-northeast3-docker.pkg.dev/nestjs-pnpm/notification/prod
        name: notification
        env:
          - name: TCP_PORT
            value: '3000'
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: 446568315939-rbrad1uogjf88fi416n82scusddm6vbu.apps.googleusercontent.com
          - name: SMTP_USER
            value: jmchung0711@gmail.com
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name : GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: google
                key: refreshToken
        ports:
          - containerPort: 3000
